# Generated by Django 3.0.8 on 2020-08-01 16:10

import code_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True, validators=[code_manager.validators.validate_code], verbose_name='Code')),
            ],
        ),
    ]
