# Generated by Django 3.0.8 on 2020-08-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
