# Generated by Django 3.1 on 2020-08-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_manager', '0002_code_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='allowed',
            field=models.CharField(choices=[('always', 'Immer'), ('alarm', 'Nach Alarm')], default='always', max_length=100, verbose_name='Erlaubt'),
        ),
        migrations.AddField(
            model_name='code',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='code',
            name='valid_after_alarm',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Gültig x Min nach Alarm'),
        ),
    ]
