# Generated by Django 3.1 on 2020-08-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_manager', '0003_auto_20200809_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'permissions': [('check_code', 'Kann Code prüfen')]},
        ),
    ]
